### ISSUE TITLE
.rbi decrypting

### ISSUE THREAD

**Issue by negan07** [pedro-n-rocha/bli223dcryptex#2]
hi trying to extract .rbi firmwares like this with no success:

https://ufile.io/r5qi9

https://ufile.io/r57z4

Is there anything else to try ?

**Comment by pedro-n-rocha** [comment]
binwalk them: 

https://ufile.io/f0ihw
https://ufile.io/b5ryy

**Comment by negan07** [comment]
perfectly extracted
